skip buildkit push test in CI due to HTTP registry
otherwise fails with:

ERROR: failed to do request: Head https://172.17.0.3:30777/v2/minikube-tests/kbld-e2e-tests-build/blobs/sha256:e14fc64dc924f68a30d6dbba9938f0a1f0a5a5211397776481dee35368b6f9ba: http: server gave HTTP response to HTTPS client